# SPDX-FileCopyrightText: 2024 Idiap Research Institute <contact@idiap.ch>
#
# SPDX-License-Identifier: BSD-3-Clause

default:
  image: python:3.12
  tags:
    - docker
    - linux

stages:
  - qa
  - build
  - test

quality:
  stage: qa
  script:
    - pip install pre-commit
    - pre-commit run --all-files

build-job:
  stage: build
  script:
    - pip install . --no-cache

test-job:
  stage: test
  script:
    - pip install .
    - python3 -m unittest discover tests
